# ============================================================
# PostgreSQL_new
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: docker.io/library/postgres:13.1
          env:
            - name: POSTGRES_PASSWORD
              value: "Passw0rd2024!"
            - name: POSTGRES_USER
              value: "reviewfilmes"
            - name: POSTGRES_DB
              value: "reviewfilmes"
          ports:
            - containerPort: 5432

---
# ============================================================
# Service PostgreSQL
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
# ============================================================
# Aplicação ReviewFilmes
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewfilmes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:

      # Necessário caso o repositório OCIR seja privado
      imagePullSecrets:
        - name: ocir-secret

      containers:
        - name: reviewfilmes

          image: gru.ocir.io/grglog7bpvjm/projeto-devops-pro:latest

          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"

            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgre;Port=5432;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rd2024!"

          ports:
            - containerPort: 8080

---
# ============================================================
# Service da aplicação
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
# ============================================================
# Ingress
# ============================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reviewfilmes
  labels:
    name: reviewfilmes
spec:
  ingressClassName: reviewfilmes-oci

  rules:
    - host: homologacao.ajotainformaticacloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reviewfilmes
                port:
                  number: 80