name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{github.actor}} em ${{github.run_number}}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: obtendo o codigo do projeto
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: wesleymlopes/desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit

  release:
    name: Criação de release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
        - name: obtendo o codigo do projeto
          uses: actions/checkout@v4

        - name: Analise do Dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: ./src/Review-Filmes.Web/Dockerfile
            output-file: ./hadolint-report.sarif
            format: sarif
            no-fail: true


        - name: Upload Hadolint para Code Scanning  
          if: always()
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: hadolint-report.sarif
            category: hadolint
        
        - name: Login to OCIR
          uses: docker/login-action@v3
          with:
            registry: gru.ocir.io
            username: ${{ secrets.OCI_USERNAME }}
            password: ${{ secrets.OCI_TOKEN }}

        - name: Build e Push da imagem docker
          uses: docker/build-push-action@v7
          with:
            push: true
            context: ./src
            file: ./src/Review-Filmes.Web/Dockerfile
            tags: |
              gru.ocir.io/grglog7bpvjm/projeto-devops-pro:v${{ github.run_number }}
              gru.ocir.io/grglog7bpvjm/projeto-devops-pro:latest

        - name: Executar o trivy
          uses: aquasecurity/trivy-action@v0.36.0
          with:
            scan-type: 'image'
            image-ref:  gru.ocir.io/grglog7bpvjm/projeto-devops-pro:v${{ github.run_number }}
            format: sarif
            output: trivy-docker-result.sarif
            severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

        - name: Upload do arquivo trivy para o github
          uses: github/codeql-action/upload-sarif@v4
          with:
            category: docker-result
            sarif_file: trivy-docker-result.sarif

  deploy-homologacao:
    needs: [release]
    uses: wesleymlopes/desafio-cicd-01/.github/workflows/deploy.yml@main
    with:
      environment-name: producao
      environment-url: http://homologacao.ajotainformaticacloud.com.br
    secrets: inherit


  

        
