name: execução de Testes
on:
  workflow_call:

jobs:
  unit-test:
    name: Teste de Unidade
    runs-on: ubuntu-latest
    steps:
      - name: obtendo o codigo do projeto
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      
      - name: Execução do Teste de Unidade
        working-directory: ./src
        run: dotnet test Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj

  integration-test:
    name: Teste de Integração
    runs-on: ubuntu-latest

    services:
      postgre:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: Passw0rd2023!
          POSTGRES_USER: review
          POSTGRES_DB: review
        ports:
          - 5432:5432
    steps:
      - name: obtendo o codigo do projeto
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"
      
      - name: Teste de Integração
        working-directory: ./src
        run: dotnet test Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
        env: 
          ConnectionStrings__DefaultConnection: "Host=localhost;Database=review;Username=review;Password=Passw0rd2023!"

  sonarqube:
    name: Scan com sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: obtendo o codigo do projeto
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Setup do jdk
        uses: actions/setup-java@v6
        with:
          distribution: adopt
          java-version: '25'

      - name: Instalação scan sonarqube
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Build and analyse
        working-directory: ./src
        run: | 
          dotnet sonarscanner begin /k:"filme" /d:sonar.host.url="http://137.131.187.93:9000"  /d:sonar.token="sqp_a7eae0406d449911d033fd15f59af42c40db6bef"
          dotnet build Review-Filmes.sln
          dotnet sonarscanner end /d:sonar.token="sqp_a7eae0406d449911d033fd15f59af42c40db6bef"
      
      



      



      
